package com.lipsum.modusoperandi.event;

public enum EventType {
    ROOM_SWITCH_REQUEST,
    ROOM_SWITCH,
    INTERACT,
    MENU_CHANGE,
    SETUP_GAME,
    KEY_EVENT,
    MOUSE_PRESS_EVENT,
    MOUSE_RELEASE_EVENT,
    MOUSE_MOVE_EVENT,
    KEY_TYPED,
    COLLISION_EVENT,
    INTERACTION_EVENT,
    DIALOGUE_EVENT,
    DIALOGUE_CONTINUE_EVENT

}
